//Part of the Unity Audio System project by Petr Yakyamsev
//github.com/doublereso/Csharp_Unity_Audio_System

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Audio;

[CreateAssetMenu(fileName = "Settings Main", menuName = "AudioCustom/Settings Main")]
public class SoAudioSetMain : ScriptableObject
{
    [Tooltip("Drop the Mixer group here")]
    public AudioMixerGroup mixerGroup;
    [Tooltip("Sets the volume to zero")]
    public bool mute;
    [Tooltip("Bypass effects applied from filter components or global listener filters")]
    public bool bypassEffects;
    [Tooltip("When set global effects on the AudioListener will not be applied to the audio signal generated by the AudioSource. Does not apply if the AudioSource is playing into a mixer group.")]
    public bool bypassListenerEffects;
    [Tooltip("When set doesn't route the signal from an AudioSource into the global reverb associated with reverb zones")]
    public bool bypassReverbZones;
    [Tooltip("If set to true, the audio source will automatically start playing on awake")]
    public bool playOnAwake;
    [Tooltip("Set whether the audio clip replays after it finishes or not")]
    public bool loop;
    [Tooltip("128 is default, 0 is highest priority")]
    [Range(0, 255)]
    public int priority = 128;

    [Space(10)]

    [Tooltip("1 is default")]
    [Range(0.0f, 1.0f)]
    public float volume = 1.0f;
    [Tooltip("1 is default")]
    [Range(0.0f, 3.0f)]
    public float pitch = 1.0f;
    [Tooltip("0 is default, -1 is left, 1 is right")]
    [Range(-1.0f, 1.0f)]
    public float stereoPan = 0.0f;
    [Tooltip("0 is 2D, 1 is 3D")]
    [Range(0.0f, 1.0f)]
    public float spatialBlend = 0.0f;
    [Tooltip("0 ignores the reverb zone, 1 acts as normal reverb zone, 1.1 boosts reverberated signal by 10dB, 1 is default")]
    [Range(0.0f, 1.0f)]
    public float reverbZoneMix = 1.0f;
}
